# This script deploys your website automatically
name: Deploy to GitHub Pages

# Only trigger this script when you push to the master branch
on:
  push:
    branches: [main]

# Specify the tasks to run when this script gets triggered
jobs:
  build:
    runs-on: ubuntu-latest

    # Download our master branch
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # You can specify your desired Node.js version here

      - name: Install dependencies
        run: npm ci # You can use `npm install` if you prefer

