name: Test

on:
  push:
    branches: [main]

jobs:
  install:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1 # Only fetch the latest commit

      - name: Set up Node.js with cache
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm" # Enable caching for npm

      - name: Install dependencies
        run: npm ci

  build:
    needs: install
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js with cache
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Build
        run: npm run build

      - name: Save build folder
        uses: actions/upload-artifact@v3
        with:
          name: build
          if-no-files-found: error
          path: build/

  test:
    needs: install
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js with cache
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"

      - name: Run tests
        run: npm test

  cypress-run:
    needs: build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download the build folder
        uses: actions/download-artifact@v3
        with:
          name: build
          path: build/

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          browser: chrome
